export const quarters = [
  { id: "Q1", label: "Q1 Check-in", window: "July", action: "Progress update" },
  { id: "Q2", label: "Q2 Check-in", window: "October", action: "Progress update" },
  { id: "Q3", label: "Q3 Check-in", window: "January", action: "Progress update" },
  { id: "Q4", label: "Q4 / Annual", window: "March / April", action: "Final achievement capture" },
];

export const thrustAreas = [
  "Customer Excellence",
  "Operational Efficiency",
  "People & Culture",
  "Innovation",
  "Compliance",
  "Financial Discipline",
];

export const uomUnits = [
  { id: "NUMERIC", label: "Numeric" },
  { id: "PERCENT", label: "%" },
  { id: "TIMELINE", label: "Timeline" },
  { id: "ZERO", label: "Zero-based" },
];

export const uomTypes = [
  { id: "MIN", label: "Higher is better" },
  { id: "MAX", label: "Lower is better" },
  { id: "TIMELINE", label: "Completion by deadline" },
  { id: "ZERO", label: "Zero means success" },
];

export function createInitialState() {
  return {
    meta: {
      activeCycleId: "cycle-2026",
      activeQuarter: "Q1",
      schemaVersion: "phase2-v1",
      seededAt: new Date().toISOString(),
    },
    users: [
      {
        id: "emp-asha",
        name: "Asha Mehta",
        email: "asha@atomquest.local",
        role: "employee",
        department: "Sales Operations",
        managerId: "mgr-ravi",
      },
      {
        id: "emp-neel",
        name: "Neel Shah",
        email: "neel@atomquest.local",
        role: "employee",
        department: "Customer Success",
        managerId: "mgr-ravi",
      },
      {
        id: "mgr-ravi",
        name: "Ravi Iyer",
        email: "ravi@atomquest.local",
        role: "manager",
        department: "Commercial",
        managerId: "admin-hr",
      },
      {
        id: "admin-hr",
        name: "Priya Nair",
        email: "priya@atomquest.local",
        role: "admin",
        department: "Human Resources",
        managerId: null,
      },
    ],
    cycles: [
      {
        id: "cycle-2026",
        name: "FY 2026 Goal Cycle",
        goalSettingOpen: "2026-05-01",
        status: "OPEN",
      },
    ],
    goalSheets: [
      {
        id: "sheet-asha-2026",
        employeeId: "emp-asha",
        managerId: "mgr-ravi",
        cycleId: "cycle-2026",
        status: "DRAFT",
        locked: false,
        managerNote: "",
        updatedAt: new Date().toISOString(),
      },
      {
        id: "sheet-neel-2026",
        employeeId: "emp-neel",
        managerId: "mgr-ravi",
        cycleId: "cycle-2026",
        status: "APPROVED",
        locked: true,
        managerNote: "Approved for Q1 tracking.",
        updatedAt: new Date().toISOString(),
      },
    ],
    goals: [
      {
        id: "goal-asha-1",
        sheetId: "sheet-asha-2026",
        thrustArea: "Financial Discipline",
        title: "Improve renewal revenue",
        description: "Increase renewal revenue from existing enterprise accounts.",
        uomUnit: "NUMERIC",
        uomType: "MIN",
        target: "1200000",
        weightage: 40,
        status: "On Track",
        sharedGoalId: null,
        readOnlyFields: [],
      },
      {
        id: "goal-asha-2",
        sheetId: "sheet-asha-2026",
        thrustArea: "Operational Efficiency",
        title: "Reduce quote turnaround time",
        description: "Bring average quote turnaround below agreed operating target.",
        uomUnit: "NUMERIC",
        uomType: "MAX",
        target: "24",
        weightage: 30,
        status: "Not Started",
        sharedGoalId: null,
        readOnlyFields: [],
      },
      {
        id: "goal-asha-3",
        sheetId: "sheet-asha-2026",
        thrustArea: "People & Culture",
        title: "Complete team enablement plan",
        description: "Finish quarterly onboarding and enablement calendar.",
        uomUnit: "TIMELINE",
        uomType: "TIMELINE",
        target: "2026-07-31",
        weightage: 30,
        status: "On Track",
        sharedGoalId: null,
        readOnlyFields: [],
      },
      {
        id: "goal-neel-1",
        sheetId: "sheet-neel-2026",
        thrustArea: "Customer Excellence",
        title: "Improve CSAT",
        description: "Lift customer satisfaction score for managed accounts.",
        uomUnit: "PERCENT",
        uomType: "MIN",
        target: "92",
        weightage: 35,
        status: "On Track",
        sharedGoalId: null,
        readOnlyFields: [],
      },
      {
        id: "goal-neel-2",
        sheetId: "sheet-neel-2026",
        thrustArea: "Compliance",
        title: "Maintain zero policy breaches",
        description: "Avoid customer data handling incidents.",
        uomUnit: "ZERO",
        uomType: "ZERO",
        target: "0",
        weightage: 25,
        status: "Completed",
        sharedGoalId: null,
        readOnlyFields: [],
      },
      {
        id: "goal-neel-3",
        sheetId: "sheet-neel-2026",
        thrustArea: "Innovation",
        title: "Launch self-service knowledge base",
        description: "Publish customer-facing self-service articles.",
        uomUnit: "TIMELINE",
        uomType: "TIMELINE",
        target: "2026-08-15",
        weightage: 40,
        status: "On Track",
        sharedGoalId: null,
        readOnlyFields: [],
      },
    ],
    goalUpdates: [
      {
        id: "update-neel-1-q1",
        goalId: "goal-neel-1",
        quarter: "Q1",
        actual: "88",
        completionDate: "",
        status: "On Track",
        updatedBy: "emp-neel",
        updatedAt: new Date().toISOString(),
      },
      {
        id: "update-neel-2-q1",
        goalId: "goal-neel-2",
        quarter: "Q1",
        actual: "0",
        completionDate: "",
        status: "Completed",
        updatedBy: "emp-neel",
        updatedAt: new Date().toISOString(),
      },
    ],
    checkIns: [
      {
        id: "checkin-neel-q1",
        employeeId: "emp-neel",
        managerId: "mgr-ravi",
        quarter: "Q1",
        cycleId: "cycle-2026",
        summary: "Strong start across customer success goals.",
        blockers: "Knowledge base delivery needs faster content review.",
        nextActions: "Prioritize article review before the Q2 check-in.",
        comment: "Strong start. Focus on knowledge base delivery pace before Q2.",
        createdAt: new Date().toISOString(),
      },
    ],
    sharedGoals: [],
    auditLogs: [
      {
        id: "audit-seed-1",
        actorId: "mgr-ravi",
        entity: "GoalSheet",
        entityId: "sheet-neel-2026",
        action: "APPROVED",
        detail: "Goal sheet approved and locked.",
        createdAt: new Date().toISOString(),
      },
    ],
    notifications: [
      {
        id: "note-1",
        userId: "mgr-ravi",
        message: "Asha Mehta updated goals.",
        type: "Approval",
        createdAt: new Date().toISOString(),
        read: false,
      },
    ],
    escalationRules: [
      { id: "esc-1", name: "Goal submission overdue", triggerAfterDays: 5, target: "Employee -> Manager -> HR" },
      { id: "esc-2", name: "Manager approval overdue", triggerAfterDays: 3, target: "Manager -> Skip-level / HR" },
      { id: "esc-3", name: "Quarterly check-in overdue", triggerAfterDays: 7, target: "Employee -> Manager -> HR" },
    ],
  };
}
